<a href="https://colab.research.google.com/github/marquesgabi/Disciplina_Metodos_Numericos_2020/blob/master/Aula_02_Met_Matematicos_ago_25_2020.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# testando primeiros
print('Hello world')
print('Hello world, I am evolving')

Hello world
Hello world, I am evolving


$x=\frac{a}{b}$

In [2]:
for k in range(2):
  for i in range(2):
    for j in range(2):
      print('k=',k,'i=',i,'j=',j)

k= 0 i= 0 j= 0
k= 0 i= 0 j= 1
k= 0 i= 1 j= 0
k= 0 i= 1 j= 1
k= 1 i= 0 j= 0
k= 1 i= 0 j= 1
k= 1 i= 1 j= 0
k= 1 i= 1 j= 1


In [3]:
for k in range(2):
  for i in range(2):
    for j in range(2):
      print('k=',k,'i=',i,'j=',j)
  print('===================')

k= 0 i= 0 j= 0
k= 0 i= 0 j= 1
k= 0 i= 1 j= 0
k= 0 i= 1 j= 1
k= 1 i= 0 j= 0
k= 1 i= 0 j= 1
k= 1 i= 1 j= 0
k= 1 i= 1 j= 1


In [4]:
x=[] # lista exemplo
for i in range(5):
  x.append(i)
print(x)

[0, 1, 2, 3, 4]


In [5]:
x=[] # lista exemplo
w=[]
for i in range(3):
  for j in range(3):
    x.append(j)
  w.append(x)
print(w)

[[0, 1, 2, 0, 1, 2, 0, 1, 2], [0, 1, 2, 0, 1, 2, 0, 1, 2], [0, 1, 2, 0, 1, 2, 0, 1, 2]]


In [6]:
 # lista exemplo
y=[]
for i in range(3):
  x=[]
  for j in range(3):
    x.append(j)
  y.append(x)
print(y)

[[0, 1, 2], [0, 1, 2], [0, 1, 2]]


In [7]:
print(y)

[[0, 1, 2], [0, 1, 2], [0, 1, 2]]


In [8]:
import pandas as pd
import numpy as np

In [9]:
df=pd.DataFrame(y)
print(df)

   0  1  2
0  0  1  2
1  0  1  2
2  0  1  2


In [10]:
mat=np.array(y)
print(mat)

[[0 1 2]
 [0 1 2]
 [0 1 2]]


In [11]:
mat[0,1]=99
print(mat)

[[ 0 99  2]
 [ 0  1  2]
 [ 0  1  2]]


In [12]:
print(mat[0,:])

[ 0 99  2]


In [13]:
print(mat[:,0])

[0 0 0]


In [14]:
# Recaptulando
# 1-tem o formato lista
# 2-tem o formato numpy array
# 3- tem o formato dataframe
# 4- indice começa no zero
# 5- tem varias situações que é possível converter formato

In [15]:
 n=5
 # lista exemplo
y=[]
for i in range(n):
  x=[]
  for j in range(n):
    x.append(j)
  y.append(x)
print(y)

[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]


In [17]:
def Lista(nn):#funcao chamamos ela por def, nn é o que vamos passar para essa funcao
  y=[]
  for i in range(nn):
    x=[]
    for j in range(nn):
      x.append(j)
    y.append(x)
  return y 

In [19]:
w=Lista(6)
print(w)

[[0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5]]


In [ ]:
#vamos usar a funcao carregando ela