<a href="https://colab.research.google.com/github/marquesgabi/Disciplina_Metodos_Numericos_2020/blob/master/Elimina_Gauss_version_01_ago_25_2020.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np
import time
import matplotlib.pyplot as plt
import numpy.linalg as npla


########################################################
# Function to decompose the matrix
# in an upper triangular form
########################################################

def LU(A,f): #LU (A,feed)
  # get the size of the system
  n = len(f)
  
  # check the size
  
  if (A.shape[0] != n) or (A.shape[1] != n): #!= e um sinal de diferente
    print('\t Inconsistent size in LU decomposition')
    info = 0
    return M,info

  # create the augmented matrix
  M = np.zeros((n,n+1)) #matriz de zeros que tem uma coluna a mais, as 3 primeiras colunas vai preencher com os valores de A e a ultima coluna com B
  M[:,:-1] = A #os dois pontos é para pegar todas a linhas
  M[:,-1] = f

  # loop through all the colum
  # to get rid of the lower part
  for iC in range(n-1):
    # for each column loop over all the lines
    # that are below the diagonal
    # to set to 0 their elements
    for iL in range(iC+1,n):
      # check if the diagonal element
      # is null
      if(M[iC,iC] == 0):
        print('\t Zero on the diagonal, LU failed')
        info = 0
        return M,info
      # eliminate the element
      M[iL,:] = M[iL,:] - M[iL,iC]/M[iC,iC] * M[iC,:]

   # if we succed we return info = 1 and the upper augmetned matrix

  info = 1
  return M,info
      

In [15]:
########################################################
# Function to backsubstitute the results
# and get the final solution
########################################################
def BS(M):
  # get the size of the matrix
  n = M.shape[0]
  # loop over all the lines
  # starting by the end
  for iL in range(n-1,-1,-1):
    # check if we have diagonal elements on the diagonal
    if(M[iL,iL] == 0):
      print('\t Zero on the diagonal, LU failed')
      info = 0
      return M,info
    # divide the line by the diagonal element of M
    M[iL,:] /= M[iL,iL]
    
    # loop over all the lines that are above this onef
    for iLL in range(iL-1,-1,-1):
      M[iLL,:] -= M[iLL,iL]*M[iL,:]

  info = 1
  return M,info

########################################################
########################################################

In [16]:
# create the matrix A
A = np. array ([[0.9 ,0.3 ,0.1] ,[0.1 ,0.5 ,0.2] , [0.0 ,0.2 ,0.7]]) #sao as porcentagens das saidas de m_metano, m_etano e m_propano. matriz a 3x3

# create the right-hand side
feed = np. array ([30.0 ,25.0 ,10.0]) #é a matriz b

M,info = LU(A,feed)
x,info = BS(M) #back substitution, vem fazendo a mesma coisa de tras pra frente

# print the solution
print(x) #matriz A é a matriz identidade, a ultima coluna é a matriz x.

[[ 1.          0.          0.         17.88461538]
 [ 0.          1.          0.         45.96153846]
 [ 0.          0.          1.          1.15384615]]


In [17]:
# check the solution
check_sol = np.dot(A,x) #multiplicacao entre 2 matrizes
print(check_sol) 

[[ 0.9  0.3  0.1 30. ]
 [ 0.1  0.5  0.2 25. ]
 [ 0.   0.2  0.7 10. ]]
